import Head from 'next/head'
import Link from 'next/link'


export default function Home() {
  return (
    <div>
      <Head>
        <title>sam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <section className=' bg-[url("http://habrastorage.org/files/90a/010/3e8/90a0103e8ec749c4843ffdd8697b10e2.jpg")] '> */}
        <section className=' bg-transparent'>
          <div className=' w-1/2 h-full mt-40 pl-20 text-white'>
            <p className=' text-8xl'>
              Welcome to FurniTech
            </p>
            <p className=' text-2xl p-5'>
              where style meet science
            </p>
            <button type="button" className =" ml-2 text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-full text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700">
              <Link href={'./products'}>
                <p className=' p-2 px-8 text-lg'>
                  Buy Now
                </p>
              </Link>
            </button>
          </div>
        </section>
      </main>
    </div>
  )
}
